language: ruby
rvm:
  - 2.5

# The `script` option is an optional list of the main build task(s). `rake` is
# the default script option for Travis and most Rails projects will want this
# when starting out as this usually runs `rake test`.

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
